# Generated by Django 5.2.4 on 2025-07-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_aboutimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_gallery_images/')),
            ],
        ),
    ]
