# Generated by Django 5.2.4 on 2025-07-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_aboutgalleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='title',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='bio',
        ),
    ]
