# Generated by Django 5.2.4 on 2025-07-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_title_speaker_designation_remove_speaker_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
